config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/publicsqaas-testing:
      branch: main
      repo: https://github.com/PalomoIFCA/publicsqaas-testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/publicsqaas-testing git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-lime-barnacle.sh
        container: qc.acc_freaky-russet-angelfish
  QC.Doc:
    repos:
      github.com/PalomoIFCA/publicsqaas-testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-blue-alligator.sh
        container: qc.doc_freaky-jade-dormouse
      github.com/PalomoIFCA/publicsqaas-testing git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-brass-panda.sh
        container: qc.doc_sloppy-ultramarine-goose
      github.com/PalomoIFCA/publicsqaas-testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-carmine-opossum.sh
        container: qc.doc_pokey-razzmatazz-binturong
  QC.Lic:
    repos:
      github.com/PalomoIFCA/publicsqaas-testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-periwinkle-bonobo.sh
        container: qc.lic_woolly-apricot-warthog
  QC.Sec:
    repos:
      github.com/PalomoIFCA/publicsqaas-testing bandit:
        commands:
        - /usr/bin/env sh .sqa/script.beady-amaranth-havanese.sh
        container: qc.sec_lanky-mustard-panda
  QC.Sty:
    repos:
      github.com/PalomoIFCA/publicsqaas-testing flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-olive-grasshopper.sh
        container: qc.sty_bluesy-pear-mouse
  QC.Uni:
    repos:
      github.com/PalomoIFCA/publicsqaas-testing pytest:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-sangria-turkey.sh
        container: qc.uni_clammy-brown-ibis
  QC.Ver:
    repos:
      github.com/PalomoIFCA/publicsqaas-testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-red-bird.sh
        container: qc.ver_pretty-ivory-maltese
timeout: 5400
